OPENAI_API_KEY = "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"


[connections.snowpark]
user = "MUNISHDWIVEDI"
password = "H00n@rtek"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "SWUWRZD.TA38830"
